name: DAPI GRPC Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '41 */160 * * *'
  release:
    types:
      - published
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
    paths:
      - packages/dapi-grpc/**
      - .github/workflows/dapi-grpc.yml

jobs:
  dapi-grpc-tests:
    name: Run DAPI GRPC tests
    uses: strophy/monoproject/.github/workflows/test.yml@master
    with:
      package: '@dashevo/dapi-grpc'
