name: Package Tests

on:
  workflow_call:
    inputs:
      package:
        description: The calling package
        type: string
        default: .

jobs:
  test:
    name: Test Dash Platform component
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Enable NPM cache
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm ci

      - name: Install Packster
        run: npm install -g packster

      - name: Run Packster
        run: packster check ${{ inputs.package }} --error

      - name: Run ESLinter
        run: npm run lint -w ${{ inputs.package }}

      - name: Get list of packages to test
        id: packster
        run: echo "::set-output name=dependants::$(packster list ${{ inputs.package }} --json)"

      - name: Run tests on packages
        run: ./scripts/run_tests.sh '${{ steps.packster.outputs.dependants }}'
